config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[destroy edit update show] 

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path, notice: "the flat was deleted"
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guest, :img_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div class="card m-3 shadow col-lg-3 rounded">
  <%= image_tag flat.img_url, alt: 'nature' ,class: "w-100"%>
  <div class="p-3 bg-light">
    <h2><%= flat.name %></h2>
    <p><%= flat.address %></p>
    <div class="d-flex justify-content-between">
      <i class="fa-solid fa-people-group ">
        <%= flat.number_of_guest %>
      </i>
      <i class="fa-solid fa-euro-sign">
        <%= flat.price_per_night %>
      </i>
    </div>
  </div>
    <div class="bg-white w-100 d-flex justify-content-between align-items-center p-3">
      <%=link_to "More info", flat_path(flat), class: "stretched-link" %>
      <%= link_to "Edit", edit_flat_path(flat)%>
      <%= link_to "Delete", flat_path(flat), data: {turbo_method: :delete}  %>
    </div>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guest %>
  <%= f.button :submit ,class: "btn btn-primary"%>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit flat</h1>
<div class="d-flex justify-content-center">
  <div class="card p-2 w-50 row h-100 justify-content-center align-items-center">
    <%= render "form", flat: @flat %>
  </div>
</div>

app/views/flats/index.html.erb
<h2 class="p-2">All our flats</h2>
<div class="d-flex grid flex-wrap justify-content-center">
  <% @flats.each do |flat| %>
      <%= render flat %>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>
<div class="d-flex justify-content-center">
  <div class="card p-2 w-50 row h-100 justify-content-center align-items-center">
    <%= render "form", flat: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container w-100 h-20 mt-2 card d-flex">
    <%= image_tag @flat.img_url, alt:"nature"%>
    <h1>Test</h1>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-secondary justify-content-between p-2 fixed-top">
  <h1 class=""><%= link_to "Simple Airbnb", flats_path ,class: "text-decoration-none link-light"%></h1>
  <%= link_to "New flat", new_flat_path, class: "text-decoration-none btn btn-outline-light p-2"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main>
    <br>
    <br>
    <br>
    <%= yield %>
    </main>
  </body>
</html>